services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: amin
      POSTGRES_PASSWORD: amin
      POSTGRES_DB: amin
    ports:
      - "5433:5432"   # <-- تغییر پورت به 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: